
export interface ISystemInfo {

    flipscreen: number;
    invertscreen: number;
    power: number,
    voltage: number,
    current: number,
    fanSpeed: number,
    temp: number,
    hashRate: number,
    bestDiff: string,
    freeHeap: number,
    coreVoltage: number,
    ssid: string,
    wifiPass: string,
    wifiStatus: string,
    versionMask: string,
    stratumQueue: number,
    asicQueue: number,
    asicResults: number,
    lastPoolError: string,
    sharesSubmitted: number,
    sharesAccepted: number,
    sharesRejected: number,
    uptimeSeconds: number,
    ASICModel: string,
    stratumURL: string,
    stratumPort: number,
    stratumUser: string,
    stratumPassword: string,
    frequency: number,
    version: string,
    invertfanpolarity: number,
    autofanspeed: number,
    fanspeed: number,
    coreVoltageActual: number,
    resetReason: string,
    haltReason: string
}